title: Jasmine's World
author: Jasmine Qu
email: mingyu.qu@outlook.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Life is short, dream and try something big!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Jasmine-Qu # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
